### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by farshidtz**
This repo has no license. 

This PR adds the Apache 2.0 license. This is to stay consistent with other EdgeX projects which all have this license.

### CODE REVIEW

**Comment by farshidtz** [comment]
I've added the contributors to approve the addition of this license. You can just start the review and approve without a comment.

I could not add Sylvain Pineau, @plars, @cwayne18. Please add yourselves as reviewer or comment.

I would merge this PR by Jan, 7th 2022 if no one objects.

Thanks

**Comment by yphus** [comment]
no problem for me +1

**Review by MonicaisHer — APPROVED** [review]

**Review by anonymouse64 — APPROVED** [review]
+1

**Review by siggiskulason — APPROVED** [review]
LGTM

**Pull request merged**
