### PR TITLE
Remove edgex-device-virtual snap if installed (latest)

### PR DESCRIPTION
**Pull request by MonicaisHer**

### CODE REVIEW

**Comment by farshidtz** [comment]
Checking whether the app exists should be done with snap info. Even if it exists, we are installing the platform from scratch and a preexisting installation of device virtual may fail to run.

Since this is a development tool, I suggest simply removing it ~~in snap_remove~~ in the beginning and at the end, installing it whenever needed.

**Comment by farshidtz** [comment]
Was there any issue with the existing approach that requires this change?

**Comment by MonicaisHer** [comment]
> Was there any issue with the existing approach that requires this change?

These failing tests might be due to uncleaned tear down of edgex-device-virtual: https://certification.canonical.com/hardware/201703-25452/submission/267397/test-results/fail/

**Comment by farshidtz** [comment]
> > Was there any issue with the existing approach that requires this change?
> 
> These failing tests might be due to uncleaned tear down of edgex-device-virtual: https://certification.canonical.com/hardware/201703-25452/submission/267397/test-results/fail/

Okay. Let's just remove it in the beginning of the test and start clean, remove again in the end.

**Review by farshidtz — APPROVED** [review]
Thanks

**Pull request merged**
